version: '3'
services:
  client:
    image: specbee/ngclient
    ports:
      - "4200-4300:4200"
      - "49153-49253:49153"
    working_dir: /usr/src/app
    volumes: 
      - ./ngclient:/usr/src/app
    environment:
        - NODE_ENV=dev
    command: npm start
    networks:
      - mean
  server:
    image: specbee/express
    ports:
      - "3000-3100:3000"
    working_dir: /usr/src/app
    volumes: 
      - ./server:/usr/src/app
    depends_on:
      - mongodb
    command: npm start
    networks:
      - mean
  mongodb:
    image: mongo
    ports:
      - "27017-27117:27017"
networks:
  mean:
    driver: bridge
